---
- name: Loading a task to check needed dependencies
  include_tasks: setup-dependencies.yml
  when: ansible_os_family == "Debian"

- name: Loading a task to install Node Version Manager
  include_tasks: setup-nvm.yml

- name: Loading a task to install Node.js
  include_tasks: setup-node.yml
