---
- name: Converge
  hosts: all

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      nodejs:
        install: true
        version: 22
      nvm:
        install: true
        script: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
        add_block: false
