---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Ensure APT package cache is updated
      ansible.builtin.apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 86400

    - name: Ensure required packages are installed
      ansible.builtin.package:
        name: "{{ dependency }}"
        state: present
      loop: "{{ nvm_dependencies }}"
      loop_control:
        loop_var: dependency

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
      nodejs:
        install: true
        version: 22
      nvm:
        install: true
        script: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh
        add_block: false
